/**
 * Reverse Sync
 *
 * Scans the codebase, updates linkage, detects drift, and appends
 * "Implementation:" / "Source:" / "Resolved in:" footers to artifacts
 * inside a fenced section that does NOT touch human-written content.
 *
 * Per plan question 9: never overwrites human prose. Only appends inside
 * <!-- godpowers:linkage:begin --> ... <!-- godpowers:linkage:end -->
 * sections per artifact, same pattern as AGENTS.md fence.
 *
 * Public API:
 *   run(projectRoot, opts) -> { scanResult, drift, footers, reviews }
 *   appendFooters(projectRoot) -> [...]
 *   buildPrdFooter(linkage) -> string
 *   buildArchFooter(linkage) -> string
 *   ...etc
 */

const fs = require('fs');
const path = require('path');

const linkage = require('./linkage');
const scanner = require('./code-scanner');
const drift = require('./drift-detector');
const reviewRequired = require('./review-required');
const impeccable = require('./impeccable-bridge');
const sourceSync = require('./source-sync');
const requirements = require('./requirements');
const state = require('./state');
const atomic = require('./atomic-write');
const artifactMap = require('./artifact-map');
const syncFs = require('./sync-fs');

const FENCE_BEGIN = '<!-- godpowers:linkage:begin -->';
const FENCE_END = '<!-- godpowers:linkage:end -->';

/**
 * Read a file, find existing fenced section. Return { exists, before, fenced, after }.
 */
function readFenced(filePath) {
  if (!fs.existsSync(filePath)) {
    return { exists: false, before: '', fenced: '', after: '' };
  }
  const content = fs.readFileSync(filePath, 'utf8');
  const beginIdx = content.indexOf(FENCE_BEGIN);
  const endIdx = content.indexOf(FENCE_END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    return { exists: true, before: content, fenced: '', after: '' };
  }
  return {
    exists: true,
    before: content.slice(0, beginIdx),
    fenced: content.slice(beginIdx + FENCE_BEGIN.length, endIdx),
    after: content.slice(endIdx + FENCE_END.length)
  };
}

/**
 * Write fenced section into a file. Idempotent.
 */
function writeFenced(filePath, sectionContent) {
  if (!fs.existsSync(filePath)) return { written: false, reason: 'file-missing' };
  const parsed = readFenced(filePath);
  const fencedBlock = `${FENCE_BEGIN}\n${sectionContent}\n${FENCE_END}`;
  let next;
  if (parsed.fenced === '') {
    // No fence yet. Append at the end.
    const sep = parsed.before.endsWith('\n\n') ? '' : (parsed.before.endsWith('\n') ? '\n' : '\n\n');
    next = `${parsed.before}${sep}${fencedBlock}\n`;
  } else {
    next = `${parsed.before}${fencedBlock}${parsed.after}`;
  }
  atomic.writeFileAtomic(filePath, next);
  return { written: true, hadFenceBefore: parsed.fenced !== '' };
}

// ============================================================================
// Per-artifact footer builders
// ============================================================================

/**
 * Build PRD footer: "Implementation:" links per requirement.
 */
function buildPrdFooter(projectRoot) {
  const fwd = linkage.readForward(projectRoot);
  const lines = [];
  lines.push('## Implementation Linkage');
  lines.push('');
  lines.push('> Auto-generated by /god-sync. Do not edit; edit your code annotations and re-sync.');
  lines.push('');
  // Group by P-MUST / P-SHOULD / P-COULD
  const groups = { 'P-MUST': [], 'P-SHOULD': [], 'P-COULD': [] };
  for (const [id, files] of Object.entries(fwd)) {
    if (linkage.classifyId(id) !== 'prd') continue;
    const tier = id.split('-').slice(0, 2).join('-'); // P-MUST, P-SHOULD, P-COULD
    if (groups[tier]) groups[tier].push({ id, files });
  }
  for (const tier of ['P-MUST', 'P-SHOULD', 'P-COULD']) {
    if (groups[tier].length === 0) continue;
    lines.push(`### ${tier} requirements`);
    lines.push('');
    for (const { id, files } of groups[tier].sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${id}** -> ${files.map(f => `\`${f}\``).join(', ')}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Build ARCH footer: Source: per container; Pattern: per ADR.
 */
function buildArchFooter(projectRoot) {
  const fwd = linkage.readForward(projectRoot);
  const lines = [];
  lines.push('## Implementation Linkage');
  lines.push('');
  lines.push('> Auto-generated by /god-sync. Do not edit.');
  lines.push('');

  const containers = [];
  const adrs = [];
  for (const [id, files] of Object.entries(fwd)) {
    const kind = linkage.classifyId(id);
    if (kind === 'container') containers.push({ id, files });
    else if (kind === 'adr') adrs.push({ id, files });
  }

  if (containers.length > 0) {
    lines.push('### Containers');
    lines.push('');
    for (const { id, files } of containers.sort((a, b) => a.id.localeCompare(b.id))) {
      const dirs = [...new Set(files.map(f => path.dirname(f)))].sort();
      lines.push(`- **${id}** (Source: ${dirs.map(d => `\`${d}\``).join(', ')})`);
    }
    lines.push('');
  }
  if (adrs.length > 0) {
    lines.push('### ADRs');
    lines.push('');
    for (const { id, files } of adrs.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${id}** Pattern: ${files.map(f => `\`${f}\``).join(', ')}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Build STACK footer: per dep, count of usage files.
 */
function buildStackFooter(projectRoot) {
  const fwd = linkage.readForward(projectRoot);
  const lines = [];
  lines.push('## Usage Linkage');
  lines.push('');
  lines.push('> Auto-generated by /god-sync. Counts of code references.');
  lines.push('');
  const stackEntries = [];
  for (const [id, files] of Object.entries(fwd)) {
    if (linkage.classifyId(id) !== 'stack') continue;
    stackEntries.push({ id, count: files.length });
  }
  if (stackEntries.length > 0) {
    for (const { id, count } of stackEntries.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${id}**: used in ${count} file(s)`);
    }
  } else {
    lines.push('(no stack-decision linkage recorded yet; add `// Implements: S-{slug}` annotations)');
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Build DESIGN footer: per token, usage count; per component, implementing files.
 */
function buildDesignFooter(projectRoot) {
  const fwd = linkage.readForward(projectRoot);
  const lines = [];
  lines.push('## Implementation Linkage');
  lines.push('');
  lines.push('> Auto-generated by /god-sync. Token usage and component implementations.');
  lines.push('');
  const tokens = [];
  const components = [];
  for (const [id, files] of Object.entries(fwd)) {
    const kind = linkage.classifyId(id);
    if (kind === 'token') tokens.push({ id, files });
    else if (kind === 'design') components.push({ id, files });
  }
  if (tokens.length > 0) {
    lines.push('### Token usage');
    lines.push('');
    for (const { id, files } of tokens.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${id}**: used in ${files.length} file(s)`);
    }
    lines.push('');
  }
  if (components.length > 0) {
    lines.push('### Components');
    lines.push('');
    for (const { id, files } of components.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${id}** Implements: ${files.map(f => `\`${f}\``).join(', ')}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Build ROADMAP footer: milestones with "Closed by:" if linked code commits known.
 * V1: just lists linked files.
 */
function buildRoadmapFooter(projectRoot) {
  const fwd = linkage.readForward(projectRoot);
  const lines = [];
  lines.push('## Implementation Linkage');
  lines.push('');
  lines.push('> Auto-generated by /god-sync. Files implementing each milestone.');
  lines.push('');
  for (const [id, files] of Object.entries(fwd)) {
    if (linkage.classifyId(id) !== 'milestone') continue;
    lines.push(`- **${id}** -> ${files.map(f => `\`${f}\``).join(', ')}`);
  }
  lines.push('');
  return lines.join('\n');
}

// ============================================================================
// Top-level orchestration
// ============================================================================

// The four .godpowers targets come from artifact-map (single source of truth
// for tier gate artifacts). Root DESIGN.md is the impeccable convention and
// stays .md; it is not resolved through the mdx/md twin logic.
function tierArtifactPath(tier) {
  const required = artifactMap.requiredArtifactsForTier(tier);
  return required && required[0] ? required[0].path : null;
}

const ARTIFACT_TARGETS = [
  { type: 'prd', path: tierArtifactPath('prd'), build: buildPrdFooter },
  { type: 'arch', path: tierArtifactPath('arch'), build: buildArchFooter },
  { type: 'roadmap', path: tierArtifactPath('roadmap'), build: buildRoadmapFooter },
  { type: 'stack', path: tierArtifactPath('stack'), build: buildStackFooter },
  { type: 'design', path: 'DESIGN.md', build: buildDesignFooter }
];

/**
 * Append fenced footers to all artifacts based on the current linkage map.
 * .godpowers targets resolve mdx-first with legacy .md fallback: the footer
 * lands in whichever file actually exists, and no file is ever created here
 * (writeFenced refuses missing files).
 */
function appendFooters(projectRoot) {
  const results = [];
  for (const t of ARTIFACT_TARGETS) {
    if (!t.path) continue;
    const resolved = t.path.startsWith('.godpowers/')
      ? syncFs.resolveArtifact(projectRoot, t.path)
      : t.path;
    const full = path.join(projectRoot, resolved);
    if (!fs.existsSync(full)) continue;
    const footer = t.build(projectRoot);
    const r = writeFenced(full, footer);
    results.push({ type: t.type, path: resolved, ...r });
  }
  return results;
}

/**
 * Run a full reverse-sync cycle.
 *
 * 1. Scan code for linkage signals
 * 2. Apply scan to linkage map
 * 3. Run drift detection
 * 4. Run impeccable detect on UI files (when installed)
 * 5. Append fenced footers to artifacts
 * 6. Sync Godpowers progress back to imported planning systems when enabled
 * 7. Surface drift findings to REVIEW-REQUIRED.md
 *
 * Returns aggregate summary.
 */
function run(projectRoot, opts = {}) {
  const scanResult = scanner.scan(projectRoot, opts);
  const applyResult = scanner.applyScan(projectRoot, scanResult);

  const driftResult = drift.detectAll(projectRoot);

  let impeccableFindings = [];
  if (opts.runImpeccable !== false) {
    const isInstalled = impeccable.isInstalled(projectRoot);
    if (isInstalled && opts.uiFiles && opts.uiFiles.length > 0) {
      for (const f of opts.uiFiles) {
        const r = impeccable.runDetect(f, { cwd: projectRoot });
        if (r.findings) impeccableFindings.push(...r.findings.map(x => ({ ...x, file: f })));
      }
    }
  }

  const footers = appendFooters(projectRoot);
  const sourceSyncResult = opts.runSourceSync === false
    ? { skipped: true, reason: 'disabled' }
    : sourceSync.run(projectRoot, opts);

  // Surface drift + impeccable findings to REVIEW-REQUIRED.md
  const reviewItems = [];
  for (const f of driftResult.findings) {
    reviewItems.push({
      severity: f.severity,
      id: f.artifactId,
      file: f.file,
      message: f.message
    });
  }
  for (const f of impeccableFindings) {
    reviewItems.push({
      severity: f.severity || 'warning',
      id: f.id || null,
      file: f.file,
      message: f.message || JSON.stringify(f)
    });
  }
  if (reviewItems.length > 0) {
    reviewRequired.appendBatch(projectRoot, {
      source: 'reverse-sync',
      summary: `${driftResult.summary.errors} drift errors, ${driftResult.summary.warnings} drift warnings, ${impeccableFindings.length} impeccable findings`,
      items: reviewItems
    });
  }

  // Refresh the deliverable ledger now that the linkage map is current. Only
  // write the file when the PRD actually declares requirements, to avoid
  // littering pre-PRD projects with an empty ledger.
  let requirementsSummary = null;
  let requirementsError = null;
  if (opts.runRequirements !== false) {
    try {
      const derived = requirements.derive(projectRoot);
      if (derived.hasRequirements) {
        const currentState = state.read(projectRoot);
        requirementsSummary = requirements.summarizeForState(
          derived,
          currentState && currentState.deliverables
        );
        // Write state.json first, then the ledger, so a state-write failure
        // cannot leave a REQUIREMENTS.md ledger that state.json never references.
        if (currentState) {
          currentState.deliverables = requirementsSummary;
          state.write(projectRoot, currentState);
        }
        requirements.writeLedger(projectRoot, derived);
      }
    } catch (e) {
      // ERR-001: surface the failure instead of swallowing it, so the caller can
      // tell a genuine requirements-step error apart from "no requirements".
      requirementsSummary = null;
      requirementsError = e.message;
    }
  }

  return {
    scanResult,
    applyResult,
    driftResult,
    impeccableFindings,
    footers,
    sourceSyncResult,
    reviewItems,
    requirements: requirementsSummary,
    requirementsError
  };
}

module.exports = {
  run,
  appendFooters,
  buildPrdFooter,
  buildArchFooter,
  buildRoadmapFooter,
  buildStackFooter,
  buildDesignFooter,
  readFenced,
  writeFenced,
  FENCE_BEGIN,
  FENCE_END,
  ARTIFACT_TARGETS
};
